# Generated by Django 5.2.7 on 2025-11-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0002_event_homepagecontent_livestream_ministry_sermon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sermon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hi.sermoncategory'),
        ),
    ]
